### ISSUE TITLE
Maintenance: Update bcjmail for Java 1.8+

### ISSUE THREAD

**Issue by boskokg** [simple-java-mail/java-utils-mail-smime#2]
Java Version Details With the arrival of Java 15. jdk15 is not quite as unambiguous as it was. The jdk18on jars are compiled to work with anything from Java 1.8 up. They are also multi-release jars so do support some features that were introduced in Java 9, Java 11, and Java 15. If you have issues with multi-release jars see the jdk15to18 release jars below.

Update dependency from 
org.bouncycastle:bcjmail-jdk15to18:1.70 
to 
org.bouncycastle:bcmail-jdk18on:1.71

**Comment by bbottema** [comment]
Will be in 2.1.0 release as soon as the PR #3 is processed.
